app = "replace-with-web-fly-app-name"
primary_region = "sjc"

[metadata]
networking_mode = "proxy"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
