[project]
name = "zubillow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "backoff>=2.2.1",
    "dotenv>=0.9.9",
    "fastmcp>=2.0.0",
    "ipython>=9.6.0",
    "load-dotenv>=0.1.0",
    "openai>=2.1.0",
    "pydantic>=2.12.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "rich>=14.2.0",
    "urllib3>=2.0.0",
]
