services:
  otp-build:
    image: opentripplanner/opentripplanner:2.5.0
    volumes:
      - ./otp/data:/var/opentripplanner
    command: ["--build", "--save"]

  otp:
    image: opentripplanner/opentripplanner:2.5.0
    volumes:
      - ./otp/data:/var/opentripplanner
    ports:
      - "8081:8080"
    command: ["--load", "--port", "8080", "--bindAddress", "0.0.0.0"]
